networks:
  dev:

services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      target: backend-dev
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      target: frontend-prod
    # develop:
    #   watch:
    #     - path: ./frontend/src
    #       action: sync
    #       target: /usr/local/app/src
    #     - path: ./client/package.json
    #       action: rebuild
    networks:
      - dev


